name: Release App
on:
  push:
    tags: "*"

env:
  IMAGE_NAME: ${DOCKER_IMAGE_NAME}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@${CHECKOUT_VERSION}
      - uses: actions-rust-lang/setup-rust-toolchain@${RUST_TOOLCHAIN_VERSION}
        with:
          toolchain: stable

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})
#Put Options Here        
      - name: Updating version
        run: sed -i -e 's/^version = .*/version = "${{ steps.get_version.outputs.VERSION }}"/' Cargo.toml

#{BUILD}

      - name: Docker login
        run: |          
          echo "${{ secrets.PUBLISH_TOKEN }}" | docker login https://ghcr.io -u "${{ github.actor }}" --password-stdin   
      - name: Docker Build and Publish
        run: |          
          docker build -t ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }} .
          docker push ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }}

