name: Test our build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@${CHECKOUT_VERSION}
      - uses: actions-rust-lang/setup-rust-toolchain@${RUST_TOOLCHAIN_VERSION}
        with:
          toolchain: stable

      - name: Build with all features     
        run: |
          cargo build --all-features

      - name: Test out our build     
        run: |
          cargo test
